### ISSUE TITLE
please any1 can help

### ISSUE THREAD

**Issue by David1ali12** [peterdotjs/tab-resize#50]
anyway to use two tabs at the same control two tabs at same time on a single tab thx

**Comment by peterdotjs** [comment]
Having two urls displaying within a single tab is not possible without using iframes. You can achieve this using this extension: https://chrome.google.com/webstore/detail/split-screen/lmccfafhibfolmpboheodclacppafddk

Tab Resize doesn't use iframes due to the many security limitations. You'll have issues with any https website which is becoming the norm. Because of these limitations tabs must be true sandboxed tabs.
