### ISSUE TITLE
Resize Chrome windows instead of tabs

### ISSUE THREAD

**Issue by fcherman** [peterdotjs/tab-resize#51]
Is it possible to include an option to resize the currently open Chrome windows instead of tabs? Perhaps it could automatically choose a layout to accommodate the number of open windows, or perhaps the user could simply specify the number of windows to tile. Or, if there's a way, perhaps the user could select which windows it wants the extension to include in the resize. That would be great!

**Comment by peterdotjs** [comment]
@fcherman apologies for the late reply, the extension by design works with tabs and not windows. There are other extensions out there like split screen which uses iframe hacks to place the splits in a single window however there are a lot of limitations around this. https sites will have issues in iframes.  

Regarding:
> perhaps the user could select which windows it wants the extension to include in the resize

You can see which windows are going to be included in the resize in the extension itself. It displays the favicon as a thumbnail and if you hover over you can actually see the website url.

**Comment by fcherman** [comment]
Peter, thanks for replying. Oddly, I can't even remember why I wanted this
behavior. LOL!
